In [52]:
from pandas import read_csv
from pandas.plotting import scatter_matrix
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
import pandas as pd
import numpy as np

In [53]:
data = read_csv('C:/Users/Simran Jakhodia/Desktop/Covid19SymptomPredictor/Cleaned-Data.csv')

In [54]:
print(data)

        Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0           1          1          1                        1            1   
1           1          1          1                        1            1   
2           1          1          1                        1            1   
3           1          1          1                        1            1   
4           1          1          1                        1            1   
...       ...        ...        ...                      ...          ...   
316795      0          0          0                        0            0   
316796      0          0          0                        0            0   
316797      0          0          0                        0            0   
316798      0          0          0                        0            0   
316799      0          0          0                        0            0   

        None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \

In [55]:
print(data.shape)

(316800, 27)


In [56]:
print(data.size)

8553600


In [57]:
print(data.head(5))

   Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Male  Gender_Transgender  Severity_Mild  Severity_Moderate  \
0            1                   0              1                  0

In [58]:
data = data.iloc[: , :-1]

In [59]:
print(data.head(5))

   Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Female  Gender_Male  Gender_Transgender  Severity_Mild  \
0              0            1                   0              1   
1   

In [60]:
print(data.groupby('Severity_Severe').size())

Severity_Severe
0    237600
1     79200
dtype: int64


In [61]:
index_no1 = data.columns.get_loc('Severity_Mild')  #TO GET COLUMN INDEX 
index_no2 = data.columns.get_loc('Severity_Moderate')
index_no3 = data.columns.get_loc('Severity_None')
index_no4 = data.columns.get_loc('Severity_Severe')
print(index_no1,index_no2,index_no3,index_no4)

19 20 21 22


In [62]:
print(data.iloc[0][20]) #to get value of cell from pandas dataframe

0


In [63]:
#data=data.loc[[0:30,13500:13580,27924:27970,56763:56800,185878:185920,283461:283500,316770:316790]]

In [64]:
#data = data.drop(columns=data.columns[5:7])

In [65]:
#data.size

In [66]:
print(data)

        Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0           1          1          1                        1            1   
1           1          1          1                        1            1   
2           1          1          1                        1            1   
3           1          1          1                        1            1   
4           1          1          1                        1            1   
...       ...        ...        ...                      ...          ...   
316795      0          0          0                        0            0   
316796      0          0          0                        0            0   
316797      0          0          0                        0            0   
316798      0          0          0                        0            0   
316799      0          0          0                        0            0   

        None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \

In [67]:
symptom = []

for i, row in data.iterrows():
    l = [data.iloc[i][19],data.iloc[i][20] ,data.iloc[i][21] ,data.iloc[i][22]];
    indexresult = l.index(max(l)) + 19 
    if indexresult == 19:
        symptom.append('Mild Severity')
                  
    if indexresult == 20:
        symptom.append('Moderate Severity') 
                  
    if indexresult == 21:
        symptom.append('No Severity') 
                  
    if indexresult == 22:
        symptom.append('Strong Severity') 
       
                       

    
data['Severity Index'] = symptom  


In [68]:
print(data.head(5))

   Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Gender_Male  Gender_Transgender  Severity_Mild  Severity_Moderate  \
0            1                   0              1                  0

In [69]:

#data = data.drop(columns=data.columns[5:7])
data = data.drop(columns=data.columns[19:23]) # To remove columns of index no. 19,20,21,22


In [70]:
print(data.head(5))

   Fever  Tiredness  Dry-Cough  Difficulty-in-Breathing  Sore-Throat  \
0      1          1          1                        1            1   
1      1          1          1                        1            1   
2      1          1          1                        1            1   
3      1          1          1                        1            1   
4      1          1          1                        1            1   

   None_Sympton  Pains  Nasal-Congestion  Runny-Nose  Diarrhea  ...  \
0             0      1                 1           1         1  ...   
1             0      1                 1           1         1  ...   
2             0      1                 1           1         1  ...   
3             0      1                 1           1         1  ...   
4             0      1                 1           1         1  ...   

   Age_20-24  Age_25-59  Age_60+  Gender_Female  Gender_Male  \
0          0          0        0              0            1   
1          0

In [71]:
data.shape

(316800, 23)

In [72]:
#print(data.describe())       [Fever,Tiredness,Dry-Cough,Difficulty-in-Breathing,Sore-Throat,None_Sympton,Pains,Nasal-Congestion,Runny-Nose,Diarrhea,]

In [73]:
print(data.groupby('Severity Index').size())

Severity Index
Mild Severity        79200
Moderate Severity    79200
No Severity          79200
Strong Severity      79200
dtype: int64


In [74]:
array = data.values
p=array[0:30,0:22]
p1=array[13500:13580,0:22]  #20
p2=array[27924:27970,0:22]
p3=array[56763:56800,0:22]
p4=array[185878:185920,0:22]
p5=array[283461:283500,0:22]
p6=array[316770:316790,0:22]
X = np.vstack([p,p1])
X = np.vstack([X,p2])
X = np.vstack([X,p3])
X = np.vstack([X,p4])
X = np.vstack([X,p5])
X = np.vstack([X,p6])
y = np.append(array[0:30,22],array[13500:13580,22])
y = np.append(y,array[27924:27970,22])
y = np.append(y,array[56763:56800,22])
y = np.append(y,array[185878:185920,22])
y = np.append(y,array[283461:283500,22])
y = np.append(y,array[316770:316790,22])

#X_train, X_validation, Y_train, Y_validation = train_test_split(X, y, test_size=0.20, random_state=1)

In [75]:
print(array)
print(X.shape[1])

[[1 1 1 ... 0 1 'Mild Severity']
 [1 1 1 ... 1 0 'Mild Severity']
 [1 1 1 ... 0 0 'Mild Severity']
 ...
 [0 0 0 ... 0 1 'No Severity']
 [0 0 0 ... 1 0 'No Severity']
 [0 0 0 ... 0 0 'No Severity']]
22


In [87]:
print(array[:,22])

['Mild Severity' 'Mild Severity' 'Mild Severity' ... 'No Severity'
 'No Severity' 'No Severity']


In [76]:
print(X)
print(y)
print(X.shape)
print(y.shape)

[[1 1 1 ... 0 0 1]
 [1 1 1 ... 0 1 0]
 [1 1 1 ... 1 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]]
['Mild Severity' 'Mild Severity' 'Mild Severity' 'Moderate Severity'
 'Moderate Severity' 'Moderate Severity' 'Strong Severity'
 'Strong Severity' 'Strong Severity' 'No Severity' 'No Severity'
 'No Severity' 'Mild Severity' 'Mild Severity' 'Mild Severity'
 'Moderate Severity' 'Moderate Severity' 'Moderate Severity'
 'Strong Severity' 'Strong Severity' 'Strong Severity' 'No Severity'
 'No Severity' 'No Severity' 'Mild Severity' 'Mild Severity'
 'Mild Severity' 'Moderate Severity' 'Moderate Severity'
 'Moderate Severity' 'Mild Severity' 'Mild Severity' 'Mild Severity'
 'Moderate Severity' 'Moderate Severity' 'Moderate Severity'
 'Strong Severity' 'Strong Severity' 'Strong Severity' 'No Severity'
 'No Severity' 'No Severity' 'Mild Severity' 'Mild Severity'
 'Mild Severity' 'Moderate Severity' 'Moderate Severity'
 'Moderate Severity' 'Strong Severity' 'Strong Severity' 'S

In [77]:
"""
# Spot Check Algorithms
models = []
models.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC(gamma='auto')))
# evaluate each model in turn
results = []
names = []
for name, model in models:
	kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
	cv_results = cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
	results.append(cv_results)
	names.append(name)
	print('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))
"""    

"\n# Spot Check Algorithms\nmodels = []\nmodels.append(('LR', LogisticRegression(solver='liblinear', multi_class='ovr')))\nmodels.append(('LDA', LinearDiscriminantAnalysis()))\nmodels.append(('KNN', KNeighborsClassifier()))\nmodels.append(('CART', DecisionTreeClassifier()))\nmodels.append(('NB', GaussianNB()))\nmodels.append(('SVM', SVC(gamma='auto')))\n# evaluate each model in turn\nresults = []\nnames = []\nfor name, model in models:\n\tkfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)\n\tcv_results = cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')\n\tresults.append(cv_results)\n\tnames.append(name)\n\tprint('%s: %f (%f)' % (name, cv_results.mean(), cv_results.std()))\n"

In [78]:
from sklearn import metrics
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import f1_score
import sklearn.model_selection as model_selection

In [79]:
from sklearn import svm, datasets

In [80]:
def svm_classifier_poly(x_train ,  x_test , y_train , y_test):
    svm_poly = svm.SVC(kernel = 'poly' , degree =3 , C = 2).fit(x_train , y_train)
    poly_pred = svm_poly.predict(x_test)
    poly_accuracy = accuracy_score(y_test , poly_pred)
    poly_f1 = f1_score(y_test , poly_pred , average = 'weighted')
    print('Accuracy (Polynomial Kernel): ', "%.2f" % (poly_accuracy*100))
    #print('Precision Score (Polynomial Kernel): ' + str(metrics.precision_score(y_test,poly_pred)*100))
    #print('Recall Score (Polynomial Kernel): ' + str(metrics.recall_score(y_test,poly_pred)*100))
    #print('F1 (Polynomial Kernel): ', "%.2f" % (poly_f1*100))
    #print('Confusion Matrix:(Polynomial Kernel) \n' + str(metrics.confusion_matrix(y_test,poly_pred)))
    return poly_pred

In [81]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split( X , y , test_size = 0.2 , random_state = 100) 
svm_classifier_poly(x_train , x_test , y_train , y_test)

Accuracy (Polynomial Kernel):  5.08


array(['Strong Severity', 'Mild Severity', 'Mild Severity',
       'Strong Severity', 'Mild Severity', 'Strong Severity',
       'Strong Severity', 'Mild Severity', 'Mild Severity',
       'Strong Severity', 'Moderate Severity', 'Moderate Severity',
       'Moderate Severity', 'Moderate Severity', 'Strong Severity',
       'Mild Severity', 'Mild Severity', 'Mild Severity',
       'Strong Severity', 'Mild Severity', 'No Severity',
       'Strong Severity', 'Mild Severity', 'Moderate Severity',
       'Strong Severity', 'No Severity', 'Strong Severity',
       'Mild Severity', 'Moderate Severity', 'Mild Severity',
       'Strong Severity', 'Mild Severity', 'No Severity', 'Mild Severity',
       'Moderate Severity', 'No Severity', 'Strong Severity',
       'Strong Severity', 'Strong Severity', 'Strong Severity',
       'Strong Severity', 'Strong Severity', 'Strong Severity',
       'Moderate Severity', 'Moderate Severity', 'No Severity',
       'Moderate Severity', 'No Severity', 'Moderat

In [82]:
from sklearn.ensemble import RandomForestClassifier
clf1 = RandomForestClassifier(n_estimators = 10000)
clf=clf1.fit(x_train , y_train)
y_predict = clf.predict(x_test)
accuracy = accuracy_score(y_test , y_predict)
#f1 = f1_score(y_test ,y_predict )
print('Accuracy (Random Forest): ', "%.2f" % (accuracy*100))
#print('Precision Score (Random Forest): ' + str(metrics.precision_score(y_test,y_predict)*100))
#print('Recall Score (Random Forest): ' + str(metrics.recall_score(y_test,y_predict)*100))
#print('F1 (Random Forest): ', "%.2f" % (f1*100))
#print('Confusion Matrix:(Random Forest) \n' + str(metrics.confusion_matrix(y_test,y_predict)))
#y_predict

Accuracy (Random Forest):  5.08


In [83]:
# Make predictions on validation dataset
model = SVC(gamma='scale')  #auto
model.fit(x_train, y_train)
predictions = model.predict(x_test)

In [84]:
print(accuracy_score(y_test, y_predict))
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict))

0.05084745762711865
[[1 6 2 4]
 [5 0 2 6]
 [5 5 1 7]
 [6 8 0 1]]
                   precision    recall  f1-score   support

    Mild Severity       0.06      0.08      0.07        13
Moderate Severity       0.00      0.00      0.00        13
      No Severity       0.20      0.06      0.09        18
  Strong Severity       0.06      0.07      0.06        15

         accuracy                           0.05        59
        macro avg       0.08      0.05      0.05        59
     weighted avg       0.09      0.05      0.06        59



# EXPORT MODEL

In [85]:
import joblib
joblib.dump(model,'covid19_prediction_model.ml')

['covid19_prediction_model.ml']

In [89]:

model.predict([['yes','yes','yes','yes','yes','yes','yes','yes','yes','no','no','no','yes','no','no','no','yes','no','no','yes','no','no']])

ValueError: could not convert string to float: 'yes'

In [ ]:

model.predict([[1,1,0,1,1,1,1,1,1,0,0,0,1,0,0,0,1,0,0,1,0,0]])